name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.4
  google_maps_flutter: ^2.12.3
  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  bloc: ^9.0.0
  http: ^1.5.0
  internet_connection_checker: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  bloc_test: ^10.0.0
  build_runner:

flutter:
  uses-material-design: true
