// Mocks generated by Mockito 5.4.6 from annotations
// in weather_app/test/bloc/bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:weather_app/weather_app.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCurrentWeatherData_0 extends _i1.SmartFake
    implements _i2.CurrentWeatherData {
  _FakeCurrentWeatherData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWeeklyWeatherData_1 extends _i1.SmartFake
    implements _i2.WeeklyWeatherData {
  _FakeWeeklyWeatherData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WeatherRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRemoteDataSource extends _i1.Mock
    implements _i2.WeatherRemoteDataSource {
  MockWeatherRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CurrentWeatherData> getCurrentWeatherData(
          _i2.PositionCoordinates? position) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentWeatherData,
          [position],
        ),
        returnValue:
            _i4.Future<_i2.CurrentWeatherData>.value(_FakeCurrentWeatherData_0(
          this,
          Invocation.method(
            #getCurrentWeatherData,
            [position],
          ),
        )),
      ) as _i4.Future<_i2.CurrentWeatherData>);

  @override
  _i4.Future<_i2.CurrentWeatherData> getCityWeatherData(String? cityName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCityWeatherData,
          [cityName],
        ),
        returnValue:
            _i4.Future<_i2.CurrentWeatherData>.value(_FakeCurrentWeatherData_0(
          this,
          Invocation.method(
            #getCityWeatherData,
            [cityName],
          ),
        )),
      ) as _i4.Future<_i2.CurrentWeatherData>);

  @override
  _i4.Future<_i2.WeeklyWeatherData> getWeeklyWeather(
          _i2.PositionCoordinates? position) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeeklyWeather,
          [position],
        ),
        returnValue:
            _i4.Future<_i2.WeeklyWeatherData>.value(_FakeWeeklyWeatherData_1(
          this,
          Invocation.method(
            #getWeeklyWeather,
            [position],
          ),
        )),
      ) as _i4.Future<_i2.WeeklyWeatherData>);
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i2.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i3.Either<_i2.WeatherAppException, _i2.PositionCoordinates>>
      getCurrentLocation() => (super.noSuchMethod(
            Invocation.method(
              #getCurrentLocation,
              [],
            ),
            returnValue: _i4.Future<
                    _i3.Either<_i2.WeatherAppException,
                        _i2.PositionCoordinates>>.value(
                _FakeEither_2<_i2.WeatherAppException, _i2.PositionCoordinates>(
              this,
              Invocation.method(
                #getCurrentLocation,
                [],
              ),
            )),
          ) as _i4.Future<
              _i3.Either<_i2.WeatherAppException, _i2.PositionCoordinates>>);
}
